document.writeln("            <footer class=footer>");
document.writeln("                <div class=copyright>");
document.writeln("                    <div>©2020-2022<a target=_blank rel=noopener title=\'夏DJ导航站\' href=http://1nav.ml>夏DJ导航站</a>&nbsp;<img src=https://xiaolongmr.github.io/test/img/icp.png width=20px height=20px alt=萌ICP备案><a title=\'萌ICP备20210214号\' href=\'//icp.gov.moe/?keyword=20210214\' target=_blank");
document.writeln("                            rel=noopener>萌ICP备20210214号</a>");
document.writeln("                        <script src=\'//pv.sohu.com/cityjson?ie=utf-8\'></script>&nbsp;&nbsp;&nbsp;欢迎来自");
document.writeln("                        <a target=_blank rel=noopener href=\'//api.vvhan.com/api/ip?s=\'>");
document.writeln("                            <script>");
document.writeln("                                document.write(returnCitySN.cname);");
document.writeln("                            </script>");
document.writeln("                        </a>的朋友&nbsp;&nbsp;&nbsp; <span id=span></span>");
document.writeln("                        <script type=text/javascript>");
document.writeln("                            function runtime() {");
document.writeln("                                X = new Date(\'6/1/2021 8:32:00\'), Y = new Date, T = Y.getTime() - X.getTime(), M = 864e5, a = T / M, A = Math.floor(a), b = 24 * (a - A), B = Math.floor(b), c = 60 * (b - B), C = Math.floor(60 * (b - B)), D = Math.floor(60 * (c - C)), span.innerHTML = \'网站已艰难运行: \' + A + \'天\' + B + \'小时\' + C + \'分\' + D + \'秒\'");
document.writeln("                            }");
document.writeln("                            setInterval(runtime, 1e3);");
document.writeln("                        </script>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </footer>");